[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "https://reverent-lamport-34e4a7.netlify.com/*"
  to = "https://victorrivera.org/:splat"

  status = 301
  force = true

[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.63.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
